# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-26 10:55


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0005_auto_20160228_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
