# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-26 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0006_auto_20160228_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(default=' ', max_length=500),
        ),
    ]
